x-env_file:
  env_file: &env_file
    - .env

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8000:8000"
    env_file: *env_file
    volumes:
      - .:/src
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - backend

  postgres:
    image: postgres:15
    container_name: postgres_container
    restart: always
    env_file: *env_file
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - backend

  redis:
    image: redis:7
    container_name: redis_container
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_container
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - backend


networks:
  backend:

volumes:
  postgres_data:
