"""add access_count to UrlShorted

Revision ID: 8020ea6b0860
Revises: 03920973d7f4
Create Date: 2025-04-15 16:25:11.964362

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8020ea6b0860"
down_revision: Union[str, None] = "03920973d7f4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "url_shortened", sa.Column("access_count", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("url_shortened", "access_count")
    # ### end Alembic commands ###
